### ISSUE TITLE
Fix MEDS stamp offsets

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#17]
Right now, sources in the MEDS stamps seem offset by (1,1) pixels. This is likely an inconsistency with the WCS origin between the coadd and the MEDS file.

**Comment by sweverett** [comment]
My very confused summary of where we are at:

1. The MEDS `obj_data` positions (taken from the detections on the coadd) are well-centered with respect to both the coadd and single-exposure images
2. The MEDS wcs info is inherited from the single exposures, and all the jacobian & row/col info is built from that.
3. The MEDS stamps are purposely made to be centered very close to the source position, within a small fraction of a pixel
4. The MEDS stamps think they are well-centered as shown below, where the red dot is the true center and the green cross is the source position from `obj_data` using the saved wcs jacobian in the meds file for this object:
![image](https://user-images.githubusercontent.com/8742179/127056079-45391e1b-0b18-4f2f-aecc-b5191f9bc735.png)
5. The GalSim `setOrigin(0,0)` call has no effect on the recovered offset r.e. the MEDS cutouts, as expected.
6. 
Despite all this, there is clearly a residual offset remaining.

**Comment by mcclearyj** [comment]
Thank you for writing this up. I have found the same off-centering issues that you have at the MEDS level. 

I'm not sure whether or not this is a clue, but when I overlay the GalSim-generated truth catalog over either the coadd or single exposure images using RA & Dec information, there is a marked offset in either case. When the GalSim-generated truth catalog is overlaid on single-image exposures using XY coordinates, rather than celestial, the offsets are much smaller. 
<img width="1190" alt="truthcat_raDec_single_exposure" src="https://user-images.githubusercontent.com/14120046/127062747-bad88b2f-5edb-4e5e-b246-2642abc2d3cc.png">
<img width="1197" alt="truthcat_XY_single_exposure" src="https://user-images.githubusercontent.com/14120046/127062766-0d44a76d-78a9-411b-82d4-b227ee32d446.png">
<img width="1200" alt="truthcat_on_single_exposure_RADec" src="https://user-images.githubusercontent.com/14120046/127062770-0c1948fd-d77e-482d-b072-87bf8e36294f.png">
<img width="1198" alt="truthcat_on_coadd_RADec" src="https://user-images.githubusercontent.com/14120046/127062775-2930bd91-40ff-4099-af11-9208894310c1.png">
