### ISSUE TITLE
Standardizing output catalog formats

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#38]
There are a few instances where we output `.csv` files instead of `.fits`, such as in `make_annular_catalog.py`. This isn't a huge deal, but it can cause some unexpected code failures such as a script assuming the input catalog is fits when using `fitsio`. Is there any reason why we cannot standardize to using `.fits` everywhere? Where might this break things?

**Comment by mcclearyj** [comment]
Agreed, output catalogs should be standardized to `.fits` format. I can start making the changes to `make_annular_catalog.py`

I think that this issue is also related to #39, and raises an interesting point :[ the block of code in question](https://github.com/superbit-collaboration/superbit-metacal/blob/4090c24d2c22982e3eb5d50c56f15d95c0528e58/superbit_lensing/shear_profiles/make_annular_catalog.py#L101) outputs a CSV file with just a few columns, rather than everything resulting from joining ngmix+metacalibration+truth+sextractor. However, it's not clear that a separate CSV file needs to be generated at all, and this block could just be removed. This would address the output catalog format in #38 

At the same time, [the selection-cut catalog](https://github.com/superbit-collaboration/superbit-metacal/blob/4090c24d2c22982e3eb5d50c56f15d95c0528e58/superbit_lensing/shear_profiles/make_annular_catalog.py#L98) has several clunky `_mcal`/`_coadd` column names that result from different ngmix+metacalibration+truth+sextractor matching steps. The following `hstack` step :
https://github.com/superbit-collaboration/superbit-metacal/blob/4090c24d2c22982e3eb5d50c56f15d95c0528e58/superbit_lensing/shear_profiles/make_annular_catalog.py#L69

could be replaced with a method to generate a new table with unique column names.

If there is agreement, I will modify `make_annular_catalog.py` accordingly.

**Comment by sweverett** [comment]
I am fine w/ removing this code block if the truncated output file is never used for anything.

For the latter point, I suggest we try substituting `hstack` for `join` - it might take a little longer to run, but our catalogs aren't that large and it will automatically take care of duplicate columns so we don't have to worry about renaming everything or removing duplicates.

**Comment by mcclearyj** [comment]
New branch `issue38` has been created to address this issue.

**Comment by mcclearyj** [comment]
Since `issue38` branch was successfully merged into `main`, I am closing this issue. We can reopen if needed.
