### ISSUE TITLE
`make_annular_catalog.py` will not run on `master`

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#39]
It appears that there is a bug [here](https://github.com/superbit-collaboration/superbit-metacal/blob/master/superbit_lensing/shear_profiles/make_annular_catalog.py#L104) in `make_annular_catalog.py` where it is trying to create new `{X/Y}_IMAGE` cols from existing `{X/Y_IMAGE_mcal` cols. However, I am pretty sure this is the opposite of what should be done. This is an easy fix, but why did this not cause a problem for your existing runs @mcclearyj ? Should one of the other annular catalog files be the default for the module? If so, we should remove deprecated files.

**Comment by mcclearyj** [comment]
I believe that this issue might be due to the output files from `make_annular_catalog.py` being supplied instead of the ngmix fits file and a truth/sextractor catalog. Here is what the call should look like:

`make_annular_catalog.py all_cl3_bg+truth_cats.ldac  gauss_mcalfit_SN5_1.1Tpsf.csv all_cl3_mcalfits.fits`

`all_cl3_bg+truth_cats.ldac` matched SExtractor coadd catalog and truth catalogs
`gauss_mcalfit_SN5_1.1Tpsf.csv` name of a CSV output file which will contain a subset of columns 
`all_cl3_mcalfits.fits` the output of the ngmix/metacalibration stage of the pipeline

Does this solve the problem? 

Also, it seems like this issue (#39) is related to the output catalog format discussed in #38.

**Comment by sweverett** [comment]
Hmm not for me - I was passing the mcal file directly:

`python make_annular_catalog.py ../tests/pipe_test/mock_coadd_cat.ldac test.fits ../tests/pipe_test/pipe_test_mcal.fits`

And getting the following error:
```
Traceback (most recent call last):
  File "make_annular_catalog.py", line 330, in <module>
    main(sys.argv)
  File "make_annular_catalog.py", line 323, in main
    metaCats.run()
  File "make_annular_catalog.py", line 290, in run
    self.shearcat = self._make_table()
  File "make_annular_catalog.py", line 102, in _make_table
    newtab.add_columns([self.mcCat['X_IMAGE_mcal'],self.mcCat['Y_IMAGE_mcal']],names=['X_IMAGE','Y_IMAGE'])
  File "/Users/sweveret/miniconda3/envs/sbmcal/lib/python3.7/site-packages/astropy/table/table.py", line 1654, in __getitem__
    return self.columns[item]
  File "/Users/sweveret/miniconda3/envs/sbmcal/lib/python3.7/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'X_IMAGE_mcal'
```

**Comment by mcclearyj** [comment]
Sorry for the trouble. For now, I suggest we incorporate a `try/except` clause here. The solution to issue #38 (using `astropy.table.join()` instead of  `astropy.table.hstack()`) may solve this problem of column name modifiers in a more general way. If it does, we can close this issue.

**Comment by mcclearyj** [comment]
New branch `issue38` has been created to address #38  and would also solve this issue
