### ISSUE TITLE
Simulated images are biased low for `g1 > 0`

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#42]
As the title says - plotting the distribution of `nfw_g1` and `nfw_g2` in the truth catalogs for background sources show a clear deficit of  galaxies where `0.0 < g1 < 0.1`:
<img width="707" alt="image" src="https://user-images.githubusercontent.com/8742179/154752664-a3205e35-3c55-4172-8e08-bd7d25c68f3d.png">
I see this for both the stacked cluster outputs from @mcclearyj 's recent test run and when I run a pipe test locally. The deficit can also be clearly seen in the shear calibration diagnostic plots:
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/8742179/154752866-1c433d34-0633-4445-812f-8efb82a38f7f.png">
This could potentially be an issue in the sampling of the COSMOS catalog in the `galsim` module

**Comment by mcclearyj** [comment]
We determined this to be an "edge effect" associated with the rectangular geometry of the SuperBIT CCD. The current image simulations incorporate the tangential shear from an NFW halo, defined as 

`g_tan = -g1*cos(2phi) - g2*sin(2phi) `

As `g1` is the ellipticity component aligned with the image axes, along the line `x = 0`, `g1` is maximally positive, while along the line `y = 0` `g1` is maximally negative. At 'X < min(Y)`, there will be an equal number of galaxies with both positive and negative `g1` values. At `X > min (Y)`, more galaxies have have negative `g1` than positive `g1`, leading to an asymmetry in the distribution of `g1` values. 

Because the `g2` ellipticity component is aligned along the lines `y = x`/`y = x `, the rectangular geometry of the detector does not result in an asymmetry in the measured `g2`.  

This can be verified with image simulations of smaller detectors.

See the following: 
![nfwtruth_polarization_moments](https://user-images.githubusercontent.com/14120046/155600058-7706726a-0c6c-4d94-bfc4-a20969120588.png)
![nfw_g1_hist_bg_gals_middetector](https://user-images.githubusercontent.com/14120046/155600096-98b2201e-3896-4679-aa94-7b9b594efe8f.png)
![truth_nfw_g1hist_smalldetector](https://user-images.githubusercontent.com/14120046/155604127-849287ea-5a09-4256-876c-f260c593c9c5.png)
![truth_nfw_g1g2_smalldetector](https://user-images.githubusercontent.com/14120046/155604129-226001cc-eade-4783-a294-beca68c3ff54.png)
